# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Garagem de Economista
email: marcelogelati@impa.br
description: > # this means to ignore newlines until "baseurl:"
  Este é meu blog pessoal para compartilhar assuntos de meu interesse,
  que tangenciam os vários assuntos da economia. Gosto muito de 
  programação, teoria econômica, filosofia da ciência, matemática, 
  psicologia e história do pensamento econômico. Tudo isso (e mais um pouco)
  será postado aqui.
baseurl: "" # the subpath of your site, e.g. /blog
url: "marcelogelati.github.io" # the base hostname & protocol for your site
twitter_username: marcelogelati
github_username:  marcelogelati

# Build settings
markdown: kramdown
